### ISSUE TITLE
Win probability?

### ISSUE THREAD

**Issue by llimllib** [sublee/trueskill#1]
I'm trying to figure out how to calculate the win probability from two TrueSkill ratings. You have draw probability, as match_quality, but not win probability.

Any idea how to calculate it? I've been reading lots of stuff on TrueSkil, but it's a bit over my head.

**Comment by jsnell** [comment]
The following seems to produce good results. (It's Jeff Moser's suggestion in the comments of http://www.moserware.com/2010/03/computing-your-skill.html, translated to Python).

    def win_probability(a, b):                                                      
        deltaMu = sum([x.mu for x in a]) - sum([x.mu for x in b])                   
        sumSigma = sum([x.sigma ** 2 for x in a]) + sum([x.sigma ** 2 for x in b])  
        playerCount = len(a) + len(b)                                               
        denominator = math.sqrt(playerCount * (BETA * BETA) + sumSigma)             
        return cdf(deltaMu / denominator)

**Comment by bichengcao** [comment]
I'm a bit confused about the winning probability regarding Beta. In Moser's article, it states that player with rating (mu+beta) can beat player with rating (mu) 80%.

But on trueskill.org, it states beta means 76% winning chance. From my testing of the code of this library, with the win_probability method jsnell@ mentioned above, it does give me 76%.

Can anyway please explain that is it suppose to be 80% or 76%?

**Comment by avdeevvadim** [comment]
@bichengcao In the Elo model the probability of a win is P = \Phi( \frac{ s_1 - s_2 }{ \sqrt{2} \beta } ) (where \Phi is the cumulative distribution function of the standard normal distribution), therefore the distance s_1 - s_2 = \beta implies P = \Phi( \frac{ 1 }{ \sqrt{2} } ) =76,02%.
In the TrueSkill model the probability of a win also depends on the variances of players: in a game with two players P = \Phi( \frac{ \mu_1 - \mu_2 - \epsilon }{ \sqrt{ \sigma_1^2 + \sigma_2^2 + 2\beta^2 } } ).
If we set \epsilon = 0, \sigma_1 = \sigma_2 = 0, \mu_1 - \mu_2 = \beta, then P also equals 76,02%, as in the Elo model.

**Comment by sublee** [comment]
@bichengcao It was @avdeevvadim's suggestion.  I called him to come.

**Comment by markbarrington** [comment]
Using the calculation for win probability formula given above I get the following....

a = ts.Rating(mu=24.0,sigma=1.0)
b = ts.Rating(mu=25.0,sigma=2.0)
print ts.quality_1vs1(a,b)
print Pwin(a,b)

0.923252184581
0.436966107024

How should I interpret this result? I would have expected that draw probability + win probability = 1 - loss probability?

**Comment by sublee** [comment]
@markbarrington Shouldn't `1 - loss probability` be same with just `win probability` rather than `draw probability + win probability`?

Best match is most fair match.  All players have almost same performance, draw probability or quality should be highest.

**Comment by markbarrington** [comment]
OK. I see from more experimenting that win_probability(a,b) = 1 - win_probability(b,a).

I don't understand how the sum of the probabilities of the possible outcomes (w,d,l) can be more than 1. I'd appreciate any insight on what I'm missing here?

**Comment by sublee** [comment]
@markbarrington Let's imagine an ideal match.  Player A and B has same win probability of 50%.  The draw probability of this match is 100%.  The sum of win probabilities and draw probability cannot be 100%.

**Comment by romovpa** [comment]
How about add [suggested](https://github.com/sublee/trueskill/issues/1#issuecomment-149762508) Moser's function as a special case? #17

**Comment by sublee** [comment]
@jsnell I've just introduced your snippet [in the documentation](http://trueskill.org/#win-probability).  Thank you for the good code.

**Comment by hayj** [comment]
> The following seems to produce good results. (It's Jeff Moser's suggestion in the comments of http://www.moserware.com/2010/03/computing-your-skill.html, translated to Python).
> 
> ```
> def win_probability(a, b):                                                      
>     deltaMu = sum([x.mu for x in a]) - sum([x.mu for x in b])                   
>     sumSigma = sum([x.sigma ** 2 for x in a]) + sum([x.sigma ** 2 for x in b])  
>     playerCount = len(a) + len(b)                                               
>     denominator = math.sqrt(playerCount * (BETA * BETA) + sumSigma)             
>     return cdf(deltaMu / denominator)  
> ```

What is the variable BETA here ?

`NameError: name 'BETA' is not defined`

**Comment by scttcper** [comment]
@hayj beta is the current global beta value, or self.beta when in the trueskill class.

https://github.com/sublee/trueskill/blob/master/trueskill/__init__.py#L47

**Comment by bernd-wechner** [comment]
> Let's imagine an ideal match. Player A and B has same win probability of 50%. The draw probability of this match is 100%. The sum of win probabilities and draw probability cannot be 100%.

This claim puzzles me as it must be drawing on some idiosyncratic definition of "win probability" not clear from the English name (the sort of thing that happens when math travels language boundaries sometimes). Because by the very definition of `probability`, `win` and `draw` is **must** be true in a two player game that:

P_winA + P_winB + P_draw = 1

as these are the three distinct possible outcomes. So if "Player A and B has same win probability of 50%." the the draw probability is by definition 0, not 100%.

I don't have a win probability coded but I did establish a predicted ranking and a confidence measure (in %) in that prediction in conversation with others and am content with that. An actual win probability I haven't looked at. Given I (and TrueSkill in general) deal with multiplayer games, win probability for each player may not be a trivial thing to calculate, not least give TrueSkill itself works on numeric approximations to PDFs. In short I'd expect that treated in papers ;-). And it may be, I have a few around and have written and summary of it all as well. Hit me up if interested.

**Comment by L0laapk3** [comment]
I'm attempting to calculate confidence intervals for the win probability.
I'm not sure if I'm doing it the right way, please correct me if I'm wrong :)

```py
def win_probability_interval(a, b, confidence):                                                      
    deltaMu = sum([x.mu for x in a]) - sum([x.mu for x in b])                   
    sumSigma = sum([x.sigma ** 2 for x in a]) + sum([x.sigma ** 2 for x in b])  
    playerCount = len(a) + len(b)                                               
    denominator = math.sqrt(playerCount * (BETA * BETA) + sumSigma)
    
    sigmaOffsetMul = ppf(confidence / 2 + .5);
    sigmaOffset = math.sqrt(sumSigma / playerCount) * sigmaOffsetMul;
    return ( cdf((deltaMu - sigmaOffset) / denominator), cdf((deltaMu + sigmaOffset) / denominator) )
```

**Comment by coldfix** [comment]
@bernd-wechner

I agree. The above snippet assumes there is no distinct outcome "draw". If you want to compute the winning probability, you would need the formula (7) from [Application and Further Development of TrueSkill™ Ranking in Sports, 2019, Ibstedt, et al](http://uu.diva-portal.org/smash/get/diva2:1322103/FULLTEXT01.pdf):

`p(p₁-p₂≥ε) = 1 - Φ((ε-µ₁+µ₂) / √(2β²+σ₁²+σ₂²)) `

For 1v1 matchup, I believe it should look like this (untested):

```python
def win_1v1(r1, r2, draw_margin, env=None):
    if env is None:
        env = global_env()
    return 1 - self.cdf(
        (draw_margin - r1.mu + r2.mu) /
        (2 * self.beta**2 + r1.sigma**2 + r2.sigma**2)
    )
```

**Comment by bernd-wechner** [comment]
Thanks enormously for the new paper. I look forward to digesting it. I am busy as can be alas. So I've added it to my library for now. I have since posting here formulated the the probability of given rankings albeit incompletely and will need to refer to my conclusions and report back when I have time. If you have time and pre-reading of the paper linked to can you determine whether or not tit is, as appears likely, constrained tot he two team scenario? Or generalised to the n team scenario.  As my needs are in the latter space.
