### ISSUE TITLE
How do I input my observed data?

### ISSUE THREAD

**Issue by vribeiro1** [sublee/trueskill#19]
The skill of the players are my latent variables, it is what I'm actually trying to estimate. The performance of each player is my observed variable.
My code initializes all the prior skills of my players, and I want to update their skills match by match given their scores. I have each player performance in the match. I see I can only input the list of skills to the rate method, and it will return me the updated skills. But how do I add my data to the code so it knows who won and who lost? In other words, how do I initialize the performance variables?

**Comment by vribeiro1** [comment]
Nevermind. I've got it. What's observed here is the teams ranking and not the players performance. Thanks!

**Comment by sublee** [comment]
Good to hear you fixed the issue yourself!

**Comment by karhohs** [comment]
Is there a road-map for implementing scores into this TrueSkill package? I found the [Score-based Bayesian Skill Learning](https://www.microsoft.com/en-us/research/wp-content/uploads/2012/01/sbsl_ecml2012.pdf) paper, but the only consider two-player or two-team games. Is this still an open question?

What do people do to combine the final scores with the TrueSkill measurements from this package?

**Comment by vribeiro1** [comment]
I am not sure but I would say it's really useful. I mean, I would better input my observed scores than the observed rank. I'll take a look to the paper you attached and see what I can get.

**Comment by sublee** [comment]
I didn't read the paper but if it doesn't consider any types of matches, I would not implement into this library.  Supporting any types of matches is the most important feature because other rating systems don't support that.

**Comment by karhohs** [comment]
@sublee I understand your reluctance. The paper I referenced is a few years old and the trail goes cold from there. I couldn't find another Microsoft Research paper that expands the concept of scoring in TrueSkill further.

I'd like to hear from someone who knows about how today's popular games, s.a. Overwatch or League Of Legends, are implementing their skill rankings. From googling around I sense TrueSkill is part of everyone's secret sauce. If some company has solved this problem perhaps they are reluctant to publish their findings, because it would disrupt how people play their game or represents some competitive advantage over other games. Does anyone have some insight on this issue?
