### ISSUE TITLE
How to get every player's 'score' using this lib?

### ISSUE THREAD

**Issue by lzeee** [sublee/trueskill#36]
Sorry to ask such simple questiones.
But how can I get the **'score'** of each player after a lot of matches?

I read the **expose** function is made for leaderboard. 
`leaderboard = sorted(ratings, key=env.expose, reverse=True)`
Does it mean that the higher the rating exposure is, the better the player is?

And can I just use the **μ** directly?

**Comment by sublee** [comment]
σ indicates uncertainty of μ. Therefore, higher μ doesn't always mean better than lower μ. We should see σ together to determine it.

For example, a never evaluated player has μ=25 because it's the default. We shouldn't assume this player is better than another player who has μ=24 but is evaluated 1 or more times. In this case, the first player's σ is higher than the second player's. `expose` penalizes on high σ. The first player's `expose` is lower than the seconds player's.

```python
>>> a
Rating(mu=25.000, sigma=8.333)
>>> b
Rating(mu=24.000, sigma=7.999)
>>> a.exposure
0.0
>>> b.exposure
0.0030000000000001137
```

**Comment by lzeee** [comment]
> σ indicates uncertainty of μ. Therefore, higher μ doesn't always mean better than lower μ. We should see σ together to determine it.
> 
> For example, a never evaluated player has μ=25 because it's the default. We shouldn't assume this player is better than another player who has μ=24 but is evaluated 1 or more times. In this case, the first player's σ is higher than the second player's. `expose` penalizes on high σ. The first player's `expose` is lower than the seconds player's.
> 
> ```python
> >>> a
> Rating(mu=25.000, sigma=8.333)
> >>> b
> Rating(mu=24.000, sigma=7.999)
> >>> a.exposure
> 0.0
> >>> b.exposure
> 0.0030000000000001137
> ```

Thanks for your reply~~
