### ISSUE TITLE
most accurate way to persist a rating to file or DB

### ISSUE THREAD

**Issue by danlangford** [sublee/trueskill#44]
im wondering what is the most accurate and preferred way to save a rating so a file or a DB. 

i can just grab the floats with rating.mu and rating.sigma?

i have also seen people persist the hex of a python float. rating.mu.hex() / rating.sigma.hex() and then later Rating(mu=float.fromhex(mu),signma=float.fromhex(sigma))

i have also seen getting the float as an int expression. (mu0,mu1) = rating.mu.as_integer_ratio() ,  (sigma0,sigma1) = rating.sigma.as_integer_ratio(). then later Rating(mu=mu0/mu1,sigma=migma0/sigma1)

i have also seen some peopl trying to just format the float with this format '.60g' and persisting that. 

do you have any advice

**Comment by sublee** [comment]
I would use a DB which can save native float64 values.

**Comment by bernd-wechner** [comment]
I have to admit the question is far too vague for a sensible answer. In what context and for what reason are you persisting them? 

For example I have a leaderboard management website that is evolving and it is using TrueSkill and this library to rate players based on results, but it uses a postgresql database for a whole swab of reasons, not just "to persist ratings". Much rather it persist ratings related to players, games and play sessions over time and is a much richer context.

How you persist these and any data depends entirely on your unmentioned context and your unmentioned goals and what you are hoping to achieve. I mean there is literally no shortage of ways you can persist two floating point numbers ... including on a piece of paper at one end to on a cloud hosted database at the other (actually perhaps the other extreme is on a stone tablet on the moon ;-) , and every single one of those methods you can achieve full precision storage too ... I mean what is it you want to do and in what context?

**Comment by danlangford** [comment]
@bernd-wechner with my current data set if i run trueskill on all the games keeping everything in memory i get a specific exposure for each player at the end. However, if i persist each resulting Rating to a database first and then pull it back out for the next game calculation the resulting exposures are different then the in-memory test. I am suspecting it has to do with precision of data persisted to the DB

my ultimate goal is to be able to have my system calculate Ratings after each game is played but i will need to persist the data in between games. So my initial question was along the lines of seeking advice around the most precise way to retreive and store the values needed to accurately recreate the Rating objects. 

But without concrete examples this is likely not helpful. ill try to put together a real example of what I am seeing

**Comment by bernd-wechner** [comment]
I have to admit I find that a decidedly odd scenario. Of what use are ratings to anyone if not persisted from the outset I wonder? I guess your in memory ratings have a long enough lifespan to be of utility in some context. But truth be told I have always saved the results of a TrueSkill update and exposed only the saved values from the moment after their generation in any case, and I use a Django FloatField which are implemented on a Postgresql backend as "double precision" fields which are stored as 8 bytes *64 bits). If you wanted arbitrary precision the postgresql type "decimal" best maps to the Python implementation of a float (which is implemented with arbitrary precision). But truth be told, no rating system is accurate enough to bother with better than double precision IMHO, and all you're after is consistency, and that seems trivial to achieve simply by never exposing a non persisted rating in the first place. In short rather than rate, expose, persist; I would run with rate, persist, expose (in fact I do). Keep Pythons arbitrary internal precision, internal to yourself and don't expose it.

**Comment by danlangford** [comment]
and you just persist the mu and sigma (+ any other non-default settings needed to recreate the Rating accurately)  ?

thanks for the insight @bernd-wechner

**Comment by bernd-wechner** [comment]
As it happens I persist mu, sigma AND most of the TrueSkill settings used in calculating them AND the rating which I define as eta; being defined by µ − (µ0 ÷ σ0) × σ. Why? Because storage is cheap and integrity is not, and integrity demands that for given rating I know the history of it, that it was arrived at with consistent TrueSkill settings and with a consistent conclusion. This I have documented here to some degree:

http://trueskill.info/help.html
